// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: vps.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuPercent        float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent     float64                `protobuf:"fixed64,3,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	UploadSpeedKbps   float64                `protobuf:"fixed64,4,opt,name=upload_speed_kbps,json=uploadSpeedKbps,proto3" json:"upload_speed_kbps,omitempty"`
	DownloadSpeedKbps float64                `protobuf:"fixed64,5,opt,name=download_speed_kbps,json=downloadSpeedKbps,proto3" json:"download_speed_kbps,omitempty"`
	Timestamp         int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuModel          string                 `protobuf:"bytes,7,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	DiskPercent       float32                `protobuf:"fixed32,8,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_vps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *StatusRequest) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *StatusRequest) GetUploadSpeedKbps() float64 {
	if x != nil {
		return x.UploadSpeedKbps
	}
	return 0
}

func (x *StatusRequest) GetDownloadSpeedKbps() float64 {
	if x != nil {
		return x.DownloadSpeedKbps
	}
	return 0
}

func (x *StatusRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatusRequest) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *StatusRequest) GetDiskPercent() float32 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

type StatusAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusAck) Reset() {
	*x = StatusAck{}
	mi := &file_vps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAck) ProtoMessage() {}

func (x *StatusAck) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAck.ProtoReflect.Descriptor instead.
func (*StatusAck) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{1}
}

func (x *StatusAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_vps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_vps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_vps_proto protoreflect.FileDescriptor

const file_vps_proto_rawDesc = "" +
	"\n" +
	"\tvps.proto\x12\x03vps\"\xac\x02\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x03 \x01(\x01R\rmemoryPercent\x12*\n" +
	"\x11upload_speed_kbps\x18\x04 \x01(\x01R\x0fuploadSpeedKbps\x12.\n" +
	"\x13download_speed_kbps\x18\x05 \x01(\x01R\x11downloadSpeedKbps\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcpu_model\x18\a \x01(\tR\bcpuModel\x12!\n" +
	"\fdisk_percent\x18\b \x01(\x02R\vdiskPercent\"%\n" +
	"\tStatusAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"E\n" +
	"\x0eCommandRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\")\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2u\n" +
	"\x03Vps\x124\n" +
	"\fReportStatus\x12\x12.vps.StatusRequest\x1a\x0e.vps.StatusAck(\x01\x128\n" +
	"\vSendCommand\x12\x13.vps.CommandRequest\x1a\x14.vps.CommandResponseB\aZ\x05../pbb\x06proto3"

var (
	file_vps_proto_rawDescOnce sync.Once
	file_vps_proto_rawDescData []byte
)

func file_vps_proto_rawDescGZIP() []byte {
	file_vps_proto_rawDescOnce.Do(func() {
		file_vps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vps_proto_rawDesc), len(file_vps_proto_rawDesc)))
	})
	return file_vps_proto_rawDescData
}

var file_vps_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vps_proto_goTypes = []any{
	(*StatusRequest)(nil),   // 0: vps.StatusRequest
	(*StatusAck)(nil),       // 1: vps.StatusAck
	(*CommandRequest)(nil),  // 2: vps.CommandRequest
	(*CommandResponse)(nil), // 3: vps.CommandResponse
}
var file_vps_proto_depIdxs = []int32{
	0, // 0: vps.Vps.ReportStatus:input_type -> vps.StatusRequest
	2, // 1: vps.Vps.SendCommand:input_type -> vps.CommandRequest
	1, // 2: vps.Vps.ReportStatus:output_type -> vps.StatusAck
	3, // 3: vps.Vps.SendCommand:output_type -> vps.CommandResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vps_proto_init() }
func file_vps_proto_init() {
	if File_vps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vps_proto_rawDesc), len(file_vps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vps_proto_goTypes,
		DependencyIndexes: file_vps_proto_depIdxs,
		MessageInfos:      file_vps_proto_msgTypes,
	}.Build()
	File_vps_proto = out.File
	file_vps_proto_goTypes = nil
	file_vps_proto_depIdxs = nil
}
